name: Build multiplataforma

on:
  push:
    branches: ["main", "multiplataforma"]
  pull_request:
    branches: ["main", "multiplataforma"]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Descargar código
        uses: actions/checkout@v4
      - name: Instalar .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - name: Restaurar dependencias
        run: dotnet restore Kiosco-Stock-Paradigma-main/StockVentas.csproj
      - name: Compilar
        run: dotnet build Kiosco-Stock-Paradigma-main/StockVentas.csproj --configuration Release --no-restore
